### ISSUE TITLE
Cardinality of Vaccination record(s) in a VC

### ISSUE THREAD

**Issue by bradhead** [bcgov/dts-vc-issuer-service#14]
Should there only be one vaccination event per VC?  Or do we model the concept of a vaccination 'card' where it holds relevant vaccinations attested by the issuer?

**Comment by swcurran** [comment]
I suspect at minimum, there would be a vaccination status credential that would show the current state of the person's vaccinations by targeted infection. A new credential would be offered each time an event occurred, and the previous credential revoked. 

There could also be a credential per event.  However, that gets into some "interesting" UX on the wallet side that has not yet been handled.   E.g. "Verifier has requested all your vaccination event credentials, do you want to share them?"

**Comment by swcurran** [comment]
Looking at the VC format proposed by others (e.g. #21 ), it definitely looks like it is a credential per vaccination event.

I suggest that the UI only allow the user to receive the latest of the string of vaccinations (e.g. where the disease or the "medicinalProductName" is the same.  Not clear how to identify the stream, but that should be the goal.
