### ISSUE TITLE
Source of Truth configurations for Issuer Controller

### ISSUE THREAD

**Issue by bradhead** [bcgov/dts-vc-issuer-service#51]
HI, With the user's ability to direct where to source vaccinations from - by way of passing the fully qualified URLs to the issuer controller we should be clear to design that the issuer controller will have a set of 'trusted' data sources by URL host base. This removes all possibility of the user from directing the controller to issue any random made up data set.   The issuer controller could serve VCs from myriad data sources provided the configurations of those are set. This way, for example, the front end for the user may aggregate records from many sources and would direct those by FQ URL to the controller.

**Comment by AnaisHebert** [comment]
Hey @bradhead, I set up the issuer controller to get the immunization data just using the guid temporarily for the demo, as the URL that is being sent ex: `http://localhost:5001/api/immunization/{guid}` , has localhost and I need it to be in this format `http://immunization-api-dev:5000/api/immunization/{guid}`
