### ISSUE TITLE
Set-up initial repository skeleton, services

### ISSUE THREAD

**Issue by esune** [bcgov/dts-vc-issuer-service#6]
Set-up a repository skeleton containing all of the required configurations to run the project in Docker.

What to include:
- Vue frontend (based on the Health Gateway tech stack)
- .NET Core api (based on the current MOH Prime tech stack)
- Aries Cloudagent Python
- PotgreSQL wallet
- PostgreSQL database (for the API, based on the current MOH Prime tech stack)
- Keycloak AIM
- PostgreSQL db for Keycloak

The agent will target BCovrin Test. To be defined whether registration will be fully automatic, or it will require user input (likely automatic, with details on what's going on). Agent seed needs to be auto-generated and persisted for future runs, unless everything is cleared: could potentially use `.env` file to store the seed value.

Vue and .NET services will NOT be scaffolded, it will just be assumed where they will be in the repository and further steps will be taken by the appropriate team/developer to fill-in with the required artifacts.

Services will be initially setup to support dev mode (hot reloading, etc.): as a nice to have, a production-like mode could also be included (will have to determine this based on the available time, it might slide to a future issue).

**Comment by bradhead** [comment]
- Vue SPA that calls agent/controller, keycloak and the vaccinations service (source of truth)
 - Vaccination Service ( HTTP READ to fetch the subjects data as JSON (ready to fold into a VC)
 - Keycloak container Github Idp activated.
