### ISSUE TITLE
QR code sometimes doesn't show up

### ISSUE THREAD

**Issue by swcurran** [bcgov/dts-vc-issuer-service#68]
We've been demoing the issuer service and it's generally working well, but sometimes the QR code does not come up when clicking the issue to the wallet button.  It's generally when retrying the walkthrough a second time, sometimes after stopping (`rm` and `stop`) and then `start`-ing the service.  Pretty sure that a refresh of the browser solves the issue, so perhaps it is data in the browser that is out of sync with persisted data(?).

We're working on getting consistent recreation instructions, but perhaps a quick scan of the code and ways that the QR code would NOT display when the button is clicked?

Thanks

**Comment by watkinspd** [comment]
Here's my experience with this when I tested again this evening:
In terminal 1
1. started ngrok

In terminal  2
1. ./manage rm
2. ./manage start

From browser
localhost:4200
login
click button to stage credential (the text notice in yellow came up saying ready to issue)
clicked button to add to wallet (nothing happened, button click did not do anything)

<img width="1567" alt="Screen Shot 2021-05-10 at 7 59 32 PM" src="https://user-images.githubusercontent.com/2670671/117752626-f6154a80-b1cb-11eb-9b5c-ba002c9179fa.png">

console log of terminal 2 showed
<img width="1067" alt="Screen Shot 2021-05-10 at 7 59 53 PM" src="https://user-images.githubusercontent.com/2670671/117752691-180ecd00-b1cc-11eb-9ad6-29509bcedcc7.png">

Quit the browser
In terminal 2
1. ctrl-c
2. ./manage stop
3. ./manage start

console log of terminal 2 at that point showed
<img width="1070" alt="Screen Shot 2021-05-10 at 8 02 50 PM" src="https://user-images.githubusercontent.com/2670671/117752798-45f41180-b1cc-11eb-9a8e-5dd24db844dc.png">

Started browser
localhost:4200
login
<img width="1558" alt="Screen Shot 2021-05-10 at 8 02 36 PM" src="https://user-images.githubusercontent.com/2670671/117752865-62904980-b1cc-11eb-9e92-de4138b1cd6e.png">

Staged the credential to add to wallet
the yellow text was displayed to say ready

console log of terminal 2 showed
<img width="1061" alt="Screen Shot 2021-05-10 at 8 03 17 PM" src="https://user-images.githubusercontent.com/2670671/117752945-86538f80-b1cc-11eb-97bc-e2da8bb19a2d.png">

Clicked to add to wallet
QR Code rendered
<img width="1567" alt="Screen Shot 2021-05-10 at 8 03 32 PM" src="https://user-images.githubusercontent.com/2670671/117753003-a08d6d80-b1cc-11eb-8b45-b81b38ee047f.png">

Console log of terminal 2 showed
<img width="1067" alt="Screen Shot 2021-05-10 at 8 03 50 PM" src="https://user-images.githubusercontent.com/2670671/117753029-aa16d580-b1cc-11eb-89c1-a513d234907e.png">

The difference I see is that in the first attempt where it failed to generate the QR Code the console log shows its last line as a call to 
HTTP POST /api/patients

Where as in the second attempt that did generate a QR Code the console log does NOT have that call in the sequence of events from app start to QR Code generation. 

This has been the pattern every time it fails. Whenever it fails to generate a QR Code the console log looks like the first log I listed above. The last line being HTTP POST /api/patients and then nothing more.

**Comment by swcurran** [comment]
Overcome by events.  Closing.
