### ISSUE TITLE
Genesis file

### ISSUE THREAD

**Issue by MosCD3** [bcgov/dts-vc-issuer-service#71]
I wonder what genesis file should I use testing with this issuer
Can I use that
https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis

**Comment by swcurran** [comment]
You should be able to do that, but you should check on the transaction that write the network -- there may be some work to do there to sign the TAA and to get/use an Endorser.  A PR was created but not merged to have the demo use the Sovrin Staging network, so some needed code changes can be found there -- https://github.com/bcgov/dts-vc-issuer-service/pull/66
